version: '3.4'
services:
  php:
    build:
      context: ./php
      args:
        - INSTALL_COMPOSER=${INSTALL_COMPOSER}
    container_name: ${PREFIX_CONTAINER_NAME}php_fpm
    networks:
      static_network:
        ipv4_address: 172.20.199.2
    ports:
      - 9000:9000
    volumes:
      - ../:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/log/:/var/www/log/
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
  nginx:
    build:
      context: ./nginx
    container_name: ${PREFIX_CONTAINER_NAME}nginx
    networks:
      static_network:
        ipv4_address: 172.20.199.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites-available
      - ./logs/nginx/:/var/log/nginx
    depends_on:
      - php
  mariadb:
    build:
      context: ./mariadb
    container_name: ${PREFIX_CONTAINER_NAME}mariadb
    networks:
      static_network:
        ipv4_address: 172.20.199.4
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/custom_my.cnf:/etc/alternatives/my.cnf
      - ./mariadb/data/:/var/lib/mysql
    depends_on:
      - php
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=docker-mysql
    command:
      --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    restart: always

   # Mailcatcher SMTP Server
  mail:
    image: jeanberu/mailcatcher:0.7.1
    container_name: ${PREFIX_CONTAINER_NAME}mail
    ports:
      # Porta para acesso ao servico de SMTP
      - 1025:1025
      # Porta para acesso ao WebMail
      - 1080:1080
    networks:
      static_network:
        ipv4_address: 172.20.199.6

networks:
  static_network:
    ipam:
      config:
        - subnet: 172.20.199.1/24
